# Generated by Django 4.2 on 2023-06-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
